# Generated by Django 3.1.7 on 2021-02-23 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('from_card', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transaction_from', to='cards.card')),
                ('to_card', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transaction_to', to='cards.card')),
            ],
        ),
    ]
